# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/db_techorg
#spring.datasource.username=sameer
spring.datasource.password=admin

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8081

# Redis connection
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=   # if you set one
spring.cache.type=redis
